### ISSUE TITLE
Code the `QuestBackend`

### ISSUE THREAD

**Issue by ferbetanzo** [CQCL/pytket-quest#4]
- Basically replicate the `QulacsBackend`.
- Bootstrap the repo to have formatting and linting checks in the CI (see ".github/workflows" in the `pytket-qulacs` repo).

Questions to answer:
- How to deal with GPU simulations?
- How to deal with simulations in multiple cores/CPUs?

**Comment by Salgi15** [comment]
Hi, I started coding the backend and I have a few questions regarding the implementation:

1. Regarding the implementation of the quantum gates, I assume that `_MEASURE_GATES`, `_ONE_QUBIT_GATES` and so on will be implemented in `quest_convert.py` in a similar way as they are in `qulacs_convert.py`, so we can use them exactly in the same way in the backend, right?

2. Regarding the density matrices and state vectors, in pyQuEST they are both handled by `Register`. In this case, is then really necessary to make the distinction between density matrices and state vectors in the simulation of the `__init__`?

3. What are exactly the predicates and why do we need them in the backend?

4. From what I understand, the functions `rebase_pass` and `default_compilation_pass` simplify and decompose the tket circuit. Therefore, there is no need to make any kind of change for them and they should be equal to the `qulacs_backend`, right?
